### PR TITLE
Cxx11SGXDemo: Fix build error

### PR DESCRIPTION
**Pull request by ffosilva**
- use Enclave.edl instead of Libcxx.edl
- Libcxx.cpp includes Enclave_t.h, not Libcxx_t.h

### CODE REVIEW

**Comment by xzhangxa** [comment]
Hi @ffosilva 

I just installed lastest linux-sgx and tried to build this project, this seems fine to build without error. Do you see build error?

But it's good change as you said it directly includes Enclave_t.h, thanks!

**Comment by ffosilva** [comment]
Hi @zhang-xin 

Without this change, I'm getting:
`
/home/ffosilva/repos/github/ffosilva/SGX-Cmake/sample/Cxx11SGXDemo/Enclave/TrustedLibrary/Libcxx.cpp:49:10: fatal error: Enclave_t.h: No such file or directory
   49 | #include "Enclave_t.h"
      |          ^~~~~~~~~~~~~
`

My environment:
cmake version 3.14.5
GCC 9.1.0
SGX SDK v2.5

**Comment by xzhangxa** [comment]
@ffosilva It's weird I cannot reproduce this in Debian testing cmake 3.13.4, gcc 8.3.0. Anyway thanks for your PR!

**Comment by ffosilva** [comment]
Hi @zhang-xin 

I was able to reproduce this behavior using a Docker image. The issue occurs only after updating GCC to v9.3.0. I don't know why older versions of GCC builds the project without any warning related to Enclave_t.h.

```
FROM ffosilva/sgx:sgx_2.5

RUN apt-get update \
 && apt-get install -y software-properties-common \
 && add-apt-repository ppa:ubuntu-toolchain-r/test \
 && apt-get install -y gcc-9 g++-9

ENV CC=gcc-9
ENV CXX=g++-9

COPY . /app/

RUN cd /app \
 && mkdir build \
 && cd build \
 && cmake .. -DBUILD_SAMPLE=ON \
 && make
```
